### ISSUE TITLE
Testresult timestamp is not set with SC parameter

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [corona-warn-app/cwa-quick-test-backend#115]
**Configuration**

WRU, URL: https://cff4f7147260.schnelltestportal.de/c19quicktest
 

**Steps:**

 1. Set quicktest result with parameter sc with postman:

POST https://testresult-5c253f79.coronawarn.app/api/v1/quicktest/results
=========================================================================
Request:
{
"testResults": [
{
"id": "f6f93810706dd586b84467950c8585f58bb928aa485aeeb556d66fb12ba55973",
"result": 6,
"sc": 1623058590
}
]
{color:#4c9aff}}

1623058590 --> 07.06.2021 - 11:36:30

 2.  Check parameter SC with postman:

POST https://testresult-5c253f79.coronawarn.app/api/v1/app/result
=========================================================================
Response:
{"testResult":6,"sc":1623069416}

 1623069416 --> 07.06.2021 - 14:36:56 (Time when the quicktest result was set)

 **Expected:**

SC has same timestamp as set in step1

**Actual:**

SC has timestamp when quicktest result was set in step1

**Comment by bergmann-dierk** [comment]
Following requests were sent:

`POST /api/v1/quicktest/results HTTP/1.1

{
"testResults": [
{
"id": "f6f93810706dd586b84467950c8585f58bb928aa485aeeb556d66fb12ba55973",
"result": 6,
"sc": 1623154064
}
]
}
`

`POST /api/v1/app/result HTTP/1.1

{
"id": "f40f49d9e0961d71970455a42dd91d5f8e54e51550bbce3e6e457fc92c6d779a"
}`

The ids did not match, therefore a new TestResult was created during the second request.

**Comment by kerstin-oppermann-tsi** [comment]
Means that the issue is obsolete? Or what does this mean? @bergmann-dierk

**Comment by ascheibal** [comment]
Issue was not reproduceable anymore. Will be closed
