### ISSUE TITLE
Provide a description for this repository

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-quick-test-backend#14]
## Current Implementation

The repository https://github.com/corona-warn-app/cwa-quick-test-backend currently doesn't have description and the [README.md](https://github.com/corona-warn-app/cwa-quick-test-backend/blob/master/README.md) is very general and doesn't explain what this repo is doing.
Even worse, the README.md says:

> This repository contains the **log upload** for the Corona-Warn-App.

## Suggested Enhancement

Remove the sentence "This repository contains the **log upload** for the Corona-Warn-App.", add a new one which explains the use of this repository and add a description. 

## Expected Benefits

Everyone understanding better what this repository is doing.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6382](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6382)

**Comment by dsarkar** [comment]
Hi @BrittaTSI 

We are updateing the readme.md files on GitHub, also for the other cwa-repositories. Could you or somebody else provide us a description for the two repositories, please?
 
For
https://github.com/corona-warn-app/cwa-quick-test-frontend 
https://github.com/corona-warn-app/cwa-quick-test-backend
I suggest:
Frontend implementation of the rapid antigen test portal for participating partners
Backend implementation of the rapid antigen test portal

Thanks.

---
Corona-Warn-App Open Source Team

**Comment by BrittaTSI** [comment]
Hi @dsarkar,

thank you for your suggestions.

For the frontend repository your proposal is is fine.

For the backend repository please use Implementation of backend for rapid antigen test portal and API for participating partners
The issues in this repo are not exclusively for the portal but also for partners who have their own portals to handle tests but offer the possibility to import the result into the CWA.

Thank you very much
Britta
P.S. I have added the same comment in the corresponding JIRA issue.

**Comment by Ein-Tim** [comment]
Thank you @dsarkar & @BrittaTSI! 
I'll add these texts to https://github.com/corona-warn-app/cwa-documentation/pull/625 ASAP!

**Comment by dsarkar** [comment]
@BrittaTSI Thanks!

**Comment by dsarkar** [comment]
@BrittaTSI This issue can be closed.  corona-warn-app/cwa-documentation#625 has been merged. Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim Right! I forgot about this, you can close your now issues! Thanks!
