### ISSUE TITLE
Which conditions trigger creation of 3-page certificate (dcc) pdf

### ISSUE THREAD

**Issue by janhoffmann** [corona-warn-app/cwa-quick-test-backend#154]
## Your Question

In our usage of the qt-frontend I noticed that in some cases a 3 page certificate (including EU DCC) is generated and can be downloaded in the result section of qt-frontend-tool.

(for reference a part of page 2:
![image](https://user-images.githubusercontent.com/1494946/128773459-b303db7d-6afb-459e-a571-85c8a5c68226.png)
)

In most of the cases only a 1 paged result is rendered, even if the user has asked for the EU-certificate and we registered the client with eu-dcc consent and first+surname in normalized form.
In my understanding this 3-page pdf should be rendered if the client asked for the certificate while registration and the test was conducted with a EU-RAT-listed test.

Even for clients where the CWA shows the test under certificates the pdf might be 1-page only.

Can we somewhere better specify when we expect a 3-page PDF and when we expect a 1-page PDF?

background:
In some cases (my estimation: 1 in 50) the result is not transmitted succesful into the app, in this cases it would be nice to have the 3-page PDF as backup, which the client could scan and add to the app.

I'm not 100% sure which repository is the correct place to ask this, if I'm wrong i kindly ask you to point me to the correct repository.

**Comment by kerstin-oppermann-tsi** [comment]
@janhoffmann did you get any clearance for your question in the meantime?

**Comment by janhoffmann** [comment]
@kerstin-oppermann-tsi no.

In Dezember the problem was not that present anymore. But I dont monitor it on a regular base anymore. Because I would have to download every single test result by hand to check that.

**Comment by kerstin-oppermann-tsi** [comment]
OK. So do you think we can close this issue here for now? And if there are any more questions you will place another issue here?

**Comment by janhoffmann** [comment]
will reopen, if I can document another case.
