### ISSUE TITLE
updateQuickTestStatus fails due to unsupported unicode character in RAT valueset 

### ISSUE THREAD

**Issue by bergmann-dierk** [corona-warn-app/cwa-quick-test-backend#156]
The current covid-19-lab-test-manufacturer-and-name valuset contains an entry with a unicode character from the "Halfwidth and Fullwidth" Forms  block.

The following entry has a fullwidth left and right paranthesis instead of a common left/right paranthesis:

`"2139":{"display":"HANGZHOU LYSUN BIOTECHNOLOGY CO., LTD., COVID-19 Antigen Rapid Test Device（Colloidal Gold）"
.......
`

During the creation of the first page of the PDF document, PDFbox throws an Exception because the characters are not available in the font:

`2021-08-11 15:11:56.312Z ERROR 34648 --- [nio-8093-exec-6] a.c.q.controller.QuickTestController     : Temporary Error Log:U+FF08 ('parenleftmonospace') is not available in this font Helvetica encoding: WinAnsiEncoding`

Entries in the valueset should use the common latin block U+0000 to U+007F.
Left Paranthesis expected character: U+0028 instead of U+FF08
Right Paranthesis expected character:  U+0029 instead of U+FF09

**Comment by ggrund-tsi** [comment]
asked ehn dcc devs: https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/122

**Comment by bergmann-dierk** [comment]
fix in https://github.com/corona-warn-app/cwa-quick-test-backend/commit/4e2a3b9647dcf60ce3aff6619ebc07f7bd79cece
Issue still open while there is no answer from ehn dcc

**Comment by kerstin-oppermann-tsi** [comment]
Tested successfully on new deployment on WRU
