### ISSUE TITLE
WRU-Server answers 502

### ISSUE THREAD

**Issue by keppla** [corona-warn-app/cwa-quick-test-backend#207]
## Description

Requesting any resource beneath https://quicktest-result-cff4f7147260.coronawarn.app/ with a valid certificate results in a 502 error code

## Expected behaviour

Depending on the operation, a successful status code, or, if the request is bad, a status code in the 4xx range

## Steps to reproduce the issue

* Have a valid certificate
* Visit  https://quicktest-result-cff4f7147260.coronawarn.app/ with a browser of your choice

## Technical details

Tried it with curl and chromium, with the wru certificate issued when accepted as partner

**Comment by f11h** [comment]
Does this problem still exist for you?

**Comment by kerstin-oppermann-tsi** [comment]
@keppla the problem still exists?
