### ISSUE TITLE
[BUG] Schnelltestportal - Testsystem "Patientendaten erfassen" fails with 500

### ISSUE THREAD

**Issue by r0bs** [corona-warn-app/cwa-quick-test-backend#212]
Since at least yesterday the Schnelltest-Portal (https://cff4f7147260.schnelltestportal.de/qt) gives me a 500 error on "Patientendaten erfassen"

![Screenshot 2021-12-17 at 13 14 49](https://user-images.githubusercontent.com/1959365/146543758-fec6ee36-8fed-48fa-af66-bc9c97fdac83.png)
)

The Request looks like this:
`
curl 'https://cff4f7147260.schnelltestportal.de/api/quicktest' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer {{ — omitted — }}' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Origin: https://cff4f7147260.schnelltestportal.de' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://cff4f7147260.schnelltestportal.de/qt/record' \
  -H 'Accept-Language: en' \
  -H 'Cookie: JSESSIONID=D4BEF70B11A1B6F3162011C3D91639E1' \
  --data-raw '{"hashedGuid":"a01208926d7a5b868c028a129abb1bdd9d7a014df90822e0131b1488e6fd18ed"}' \
  --compressed
`

and the response like this:
`
{
    "timestamp": "2021-12-17T12:14:34.393+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/quicktest"
}
`

**Comment by r0bs** [comment]
I am still seeing this behaviour. Is there anything I could to to circumvent this?

**Comment by kerstin-oppermann-tsi** [comment]
@r0bs please can you recheck, I can not recognized the behaviour just now.

**Comment by r0bs** [comment]
Hi Kerstin! Thx a lot for your reply. I am still seeing this error. Could you maybe check the server logs? Here is a recent response incl. timestamp of one of those 500ers:
`{
    "timestamp": "2022-01-04T23:03:58.014+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/quicktest"
}`

**Comment by kerstin-oppermann-tsi** [comment]
Hi @r0bs I will redirect this to one of our developers.

**Comment by kerstin-oppermann-tsi** [comment]
@r0bs We found out a possible reason that your groupname (Teststelle) ist too long. I did some tests, when I choose a Teststelle with 48 characters I got 500, when I choose a teststelle  with 47 characters it works. Whats your name of your Teststelle?
At the moment we dont know why this is at it is ....

**Comment by kerstin-oppermann-tsi** [comment]
As quickfix we set the groupname length to maximum 45 in the frontend.

**Comment by r0bs** [comment]
Hi Kerstin! After changing the name of the Teststelle to 45 chars, it is now working as expected! :) Thanks a lot.
