### ISSUE TITLE
Standardized name incorrect (BRK)

### ISSUE THREAD

**Issue by sicheste** [corona-warn-app/cwa-quick-test-backend#213]
## Describe the bug

I've been tested three times in the last weeks and always with the same problem: My last name of the standardized name in the certificate is incorrect. Lets say my name would be Max Mustermann. Then the CWA is showing `Mustermann, Max` as Name and First Name. But the field for the standardized name shows something like `MUSTIRMANN<<MAX` - almost correct, but still incorrect.

<img src=https://user-images.githubusercontent.com/7395079/148061514-690e1617-e597-4230-8ba5-a5ccf6c4d57e.png width=50% height=50%>

## Expected behaviour

I would expect to have the standardized name as `MUSTERMANN<<MAX` in this case.

## Steps to reproduce the issue

Create your personal QR code on https://meintest.brk.de, get tested (quick test) and receive the QR code for the CWA along with your test result (depending on test station, you have to book an appointment to get a certificate for CWA). Scan the QR code with CWA to fetch the certificate. The standardized name is shown incorrect in my case.

## Technical details

Android 12, CWA 2.14.1

## Additional context

This happened now the third time. At the first time I guessed that at the test station my name was written in correct. But then it was the same after the second test. I already contacted the BRK (testservice@<organization>). They checked on their side for my two tests and told me, that on their side everything is fine. It has to be something on CWA side.

Today I was again at the test station. There I asked whether they can specifically check again the name since it was incorrect the last times. I showed her the certificate on my smartphone from the last check, to explain what to look for. She told me that she does not have a separate field and everything was fine. The certificate is now again having the incorrect name.

I found https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme-ohne-DCC and had a look on my personal link (`https://s.coronawarn.app?v=1#...`). Decoding it is giving the correct name, but this is not containing the standardized version. It is not explained on that page how the standardized name is created / provided.

I have changed the given example, since actually the `E` in my name is replaced by `I`. The example is now showing this.

**Comment by kerstin-oppermann-tsi** [comment]
@sicheste  I think you have to place this issue to the partner where you was tested. Because I tried to recognize your issue in our testsystem and for me it works correct. This is the standardized name I got for Max Mustermann:
![image](https://user-images.githubusercontent.com/81565834/148037857-3a3b5cdf-2876-4992-9151-b614680078b9.png)

Maybe ther is an issue in the partners solution of creating standardized name.

**Comment by ascheibal** [comment]
Also the third angle bracket seems wrong in this case. We will hand over this to the BRK.
Thanks @sicheste for pointing this out.

**Comment by sicheste** [comment]
@ascheibal Oh, sorry. That's my fault. It is only showing `<<`. The angle brackets are fine. I will fix it in the description.

Would be great if you (=someone from CWA) could contact the BRK. As I wrote, I already tried and failed on the first level support.

For me it is unclear where this error is happening in detail, but I also do not have to know, would only help when I have to talk to the BRK support again :)

**Comment by sicheste** [comment]
@ascheibal I have been today again on a BRK test center. Now the certificate is fine, the name is correct.

Thanks for forwarding this issue to the BRK, seems they fixed it. I am closing the ticket.

**Comment by ascheibal** [comment]
> @ascheibal I have been today again on a BRK test center. Now the certificate is fine, the name is correct.
> 
> 
> 
> Thanks for forwarding this issue to the BRK, seems they fixed it. I am closing the ticket.
Hi @sicheste,
Unfortunately this Standardized/ICAO Name transliteration feature in the quicktest portal still got no prioritization! So the feature is still on our mind but waits for implementation.
You were lucky, the people at your Testcenter this time paid more attention on preventing typos.(Which was actually the ´fix´) We know that incorrect spelling is now an even more severe issue, as CWA figures out vaxination/booster state and reads incorrect spelling as certificates of two different individuals rather than showing your correct vax. state. So keep fingers crossed on this.

**Comment by sicheste** [comment]
Hello @ascheibal 
> You were lucky, the people at your Testcenter this time paid more attention on preventing typos.(Which was actually the ´fix´) We know that incorrect spelling is now an even more severe issue, as CWA figures out vaxination/booster state and reads incorrect spelling as certificates of two different individuals rather than showing your correct vax. state. So keep fingers crossed on this.

This is not valid for the test center of the BRK. When I, as a person to be tested, arrive there, they scan a QR code which I generated before (it is speeding up the process of entering name, birth date etc. - and of course, this is not the QR code which can be generated by the CWA app). They check the entered data - but there is no field for the standardized/ICAO name.

Now they are having two screens, one for the personnel, and which is facing to the person to be tested. Therefore I was able to see the web form. There is no field to give the standardized name. There must be other magic doing this later on - and for me it seems that this magic was corrected.

> Unfortunately this Standardized/ICAO Name transliteration feature in the quicktest portal still got no prioritization! So the feature is still on our mind but waits for implementation.

Would make sence to have it on long term. For now: what ever was changed is working now :)

**Comment by vaubaehn** [comment]
Hi @sicheste ,
there is a request to harmonize "the magic of ICAO transliteration" across all participating parties, including RAT portal and test centers with their own applications that are connected via the API: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185#issuecomment-1021142950
