### ISSUE TITLE
Importing and manually setting the DCC flag at test centers is not possible

### ISSUE THREAD

**Issue by fibis** [corona-warn-app/cwa-quick-test-backend#222]
## Describe the bug

When uploading a list of test enters or edit a test center manually via map admin, it is not possible to set the dcc flag to true. The preview of the import shows these values correctly, but they are not saved correctly.

## Expected behaviour
If the import says "Ja" for dcc or when I edit a test center and check the dcc box, it should be saved with dcc enabled.

## Steps to reproduce the issue

1. Go to the map admin
2. Open a test center that didn't have dcc
3. Check the dcc box and save the entry
4. After saving, the dcc flag is still false

**Comment by kerstin-oppermann-tsi** [comment]
@fibis what do you mean with dcc flag in test center? There is no such field.

**Comment by fibis** [comment]
To  mark test centers with the dcc flag (the test center issues dcc certificates), it is necessary to be unlocked for this.
