### ISSUE TITLE
BUG - 400 when registering testname that becomes longer than 200 characters after encryption while saving

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [corona-warn-app/cwa-quick-test-backend#224]
When registering a DCC test the testname becomes longer than 200 characters because it is encryted.

![image](https://user-images.githubusercontent.com/81565834/152371447-77a3b61c-fe0d-4a51-acff-d3007b160c7a.png)
![image](https://user-images.githubusercontent.com/81565834/152372528-94b420e6-93c5-448a-be38-0ae067886455.png)

**Solution:**
Testname should not be encrypted. So the length should hopefully not reach the maximum length of 200 chars.

**Comment by kerstin-oppermann-tsi** [comment]
Issue is quick fixed by frontend, cutting the description (name of test) to 100 characters

**Comment by ahodzic2** [comment]
@kerstin-oppermann-tsi Does this continue to be an issue? If so, and no one is currently working on this, I would volunteer to work on this.

**Comment by kerstin-oppermann-tsi** [comment]
@ahodzic2 as you can see this issue is fixed by the frontend fix and is delivered and additionally an information should send out to the test manufacturers the testnames should be shorter.
We forgot to close this issue here.
