### ISSUE TITLE
bug: testcenter is still shown on the map after the partner-contract has been cancelled and the test-data has been downloaded

### ISSUE THREAD

**Issue by ascheibal** [corona-warn-app/cwa-quick-test-backend#268]
## Describe the bug

Testcenter is still shown on the map after the partner-contract has been cancelled and the test-data has been downloaded

## Expected behaviour

The test-center can no longer be found on the map after cancellation date is due.

## Steps to reproduce the issue

1. Partner contract for partner _test1020_ has been cancelled (cancellation date on 19.10.22), Addition of tests and test-results is no longer possible with the QT-Portal.

2. The test-data for the partner has been downloaded in the QT-Portal.

3. The Testcenter was previously shown on the map and is not removed.

**Comment by f11h** [comment]
fixed by linked PR
