### ISSUE TITLE
Archivdatenzugang

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-backend#95]
Anforderungen dringend zu klären
@jensmuehlner hatte eMail-Verkehr zum Thema

**Comment by BrittaTSI** [comment]
Umsetzung vom Team Hornet angefangen, Status unklar.
@joerg-oppermann-tsi - wer kümmert sich darum?

**Comment by BrittaTSI** [comment]
Abstimmungen per eMail mit Security und Datenschutz sind erfolgt. 
Vollständigkeit und Widerspruchsfreiheit der Anforderungen zu klären.

**Comment by BrittaTSI** [comment]
Anforderungen aus Sicht Fachseite & Scoping :

- Daten müssen 10 Jahre im Langzeitarchiv vorgehalten werden
- Daten müssen stark verschlüsselt sein
- Patient hat Recht auf Auskunft über seine gespeicherten Daten (Anfrage bei Teststelle oder ggf. direkt bei uns)
  -> Die verschlüsselte DB muß mit vertretbarem Aufwand durchsuchbar sein. Hier wäre problematisch, wenn z.B. komplette DB verschlüsselt wird und alle Inhalte vollständig entschlüsselt werden müssen, um eine Auskunft zu erteilen. Es müssen also einzelne Elemente separat verschlüsselt werden um durchsuchbar zu sein
  -> Durchsuchbarkeit darf allerdings zu keiner Schwächung der Verschlüsselung führen.
- Ggf. fordert auch der Teststellenbetreiber die Herausgabe aller Daten an, die in seiner Teststelle erhoben wurden.

**Comment by ascheibal** [comment]
solved with cancellation feature
