### ISSUE TITLE
Anpassung an EU Green Certificate (Schnittstelle)

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-quick-test-backend#97]
Änderungsbedarf von Hr. Benzler, RKI, ausgesprochen im Backlog-Prep-Meeting, 29.04.

@jensmuehlner - sind das hier die Anforderungen der EU? ´: https://miro.com/app/board/o9J_lOjvz8M=/?moveToWidget=3074457357645041025&cot=14

**Comment by BrittaTSI** [comment]
https://telekom.sharepoint.de/sites/DigitalCoronaDefenseTribe/_layouts/OneNote.aspx?id=%2Fsites%2FDigitalCoronaDefenseTribe%2FSiteAssets%2FNotizbuch%20f%C3%BCr%20Digital%20Corona%20Defense%20Tribe&wd=target%28CWA.one%7C5766ABEC-D949-4A0E-8BC2-C8BE396642DF%2FDGC%40CWA%7C72B78B25-7239-47BB-95D7-64AAA72DF784%2F%29

**Comment by a-trzewik** [comment]
See branch: https://github.com/corona-warn-app/cwa-quick-test-backend/tree/feat/dgc

**Comment by a-trzewik** [comment]
I see following task to do
- add scheduler annotation to app.coronawarn.quicktest.service.DccService also config for this scheduler in config
- add needed data (for examle fnt, gnt) to QuickTest entity and also DTO object for frontend 
  - app.coronawarn.quicktest.domain.QuickTest
  - app.coronawarn.quicktest.model.QuickTestPersonalDataRequest
- Add dcc fields for app.coronawarn.quicktest.domain.QuickTest
 - publicKey
 - dccUploadData
 - dcc - (certificate qrcode string)
 - dccStatus (needPublicKey, pendingUpload, pendingSignature, finieshed)
- Implement DccServer Client and all DTO Objects app.coronawarn.quicktest.client.DccServerClient
- Finish JSON Builder eu.europa.ec.dgc.DccTestBuilder (validate JSON Data)
- Update doc
- Update Junits
- refactoring use dgc-gen-lib as dependency mode dcc code to this lib
- (Open Question In scope?) generate dcc without corona warnapp and send it per Email (different workflow)
